# Generated by Django 3.0 on 2021-03-13 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0008_remove_allcourses_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 10, 31, 52, 528228, tzinfo=utc), verbose_name='Started from'),
            preserve_default=False,
        ),
    ]
